import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { CleanupOptions, RunnerRecord } from '../../shared/types';
import { targetUrl } from '../github';
import { isWin, LEADING_BOM, type Step } from './exec';

const HOOK_KEY = 'ACTIONS_RUNNER_HOOK_JOB_COMPLETED';
const HOOK_FILE = isWin ? 'grc-job-completed.ps1' : 'grc-job-completed.sh';
/** Files the runner writes when it is configured. */
const CONFIG_FILES = [
  '.runner',
  '.credentials',
  '.credentials_rsaparams',
  '.service',
];

export const NAME_RE = /^[A-Za-z0-9._-]{1,64}$/;
export const LABEL_RE = /^[A-Za-z0-9._-]{1,100}$/;

function readJson<T>(file: string): T | null {
  try {
    // The runner writes these files with a BOM on Windows.
    return JSON.parse(
      fs.readFileSync(file, 'utf8').replace(LEADING_BOM, ''),
    ) as T;
  } catch {
    return null;
  }
}

export function isExtracted(dir: string): boolean {
  return fs.existsSync(
    path.join(dir, 'bin', isWin ? 'Runner.Listener.exe' : 'Runner.Listener'),
  );
}

export function readRunnerFile(
  dir: string,
): { agentId: number; agentName: string } | null {
  return readJson(path.join(dir, '.runner'));
}

/** The OS service name the runner recorded when it was installed as a service. */
export function readServiceName(dir: string): string | null {
  try {
    return (
      fs
        .readFileSync(path.join(dir, '.service'), 'utf8')
        .replace(LEADING_BOM, '')
        .trim() || null
    );
  } catch {
    return null;
  }
}

export function runnerVersion(dir: string): string | undefined {
  // bin/ contains e.g. Runner.Listener.deps.json with "Runner.Listener/2.337.0".
  const deps = readJson<{ targets?: Record<string, Record<string, unknown>> }>(
    path.join(dir, 'bin', 'Runner.Listener.deps.json'),
  );
  for (const t of Object.values(deps?.targets ?? {})) {
    for (const k of Object.keys(t)) {
      const m = /^Runner\.Listener\/(\d+\.\d+\.\d+)/.exec(k);
      if (m) return m[1];
    }
  }
  return undefined;
}

function listenerStep(dir: string, args: string[], token: string): Step {
  // config.sh also prepares .env and checks dependencies on Linux.
  return isWin
    ? {
        file: path.join(dir, 'bin', 'Runner.Listener.exe'),
        args,
        cwd: dir,
        env: { ACTIONS_RUNNER_INPUT_TOKEN: token },
      }
    : {
        file: path.join(dir, 'config.sh'),
        args,
        cwd: dir,
        env: { ACTIONS_RUNNER_INPUT_TOKEN: token },
      };
}

export interface ConfigureOptions {
  token: string;
  replace?: boolean;
  /** Windows only: install as a service during configuration. */
  windowsService?: { account?: string; password?: string };
}

/** Registers the runner. Secrets travel as ACTIONS_RUNNER_INPUT_* env vars, never on the command line. */
export function configureStep(r: RunnerRecord, opts: ConfigureOptions): Step {
  const args = [
    'configure',
    '--unattended',
    '--url',
    targetUrl(r.target),
    '--name',
    r.name,
    '--work',
    '_work',
  ];
  if (r.labels.length) args.push('--labels', r.labels.join(','));
  if (r.target.kind === 'org' && r.runnerGroup)
    args.push('--runnergroup', r.runnerGroup);
  if (opts.replace) args.push('--replace');
  const step = listenerStep(r.dir, args, opts.token);
  if (opts.windowsService) {
    args.push('--runasservice');
    const { account, password } = opts.windowsService;
    if (account) {
      args.push('--windowslogonaccount', account);
      step.env = {
        ...step.env,
        ACTIONS_RUNNER_INPUT_WINDOWSLOGONPASSWORD: password ?? '',
      };
    }
  }
  return step;
}

/** Deregisters the runner from GitHub and deletes its local configuration (and Windows service). */
export function removeStep(dir: string, token: string): Step {
  return listenerStep(dir, ['remove'], token);
}

/** Deletes configuration files left behind when `remove` could not reach GitHub. */
export async function clearConfigFiles(dir: string) {
  await Promise.all(
    CONFIG_FILES.map((f) => fs.promises.rm(path.join(dir, f), { force: true })),
  );
}

function hookScript(c: CleanupOptions): string {
  if (isWin) {
    const clear = (expr: string) =>
      `if (${expr} -and (Test-Path -LiteralPath ${expr})) { Get-ChildItem -LiteralPath ${expr} -Force | Remove-Item -Recurse -Force }`;
    return [
      '# Generated by GRC Self-Host. Runs after every job; keeps the runner registration.',
      "$ErrorActionPreference = 'SilentlyContinue'",
      clear('$env:GITHUB_WORKSPACE'),
      clear('$env:RUNNER_TEMP'),
      ...(c.actions
        ? [clear("(Join-Path $PSScriptRoot '_work\\_actions')")]
        : []),
      ...(c.tool ? [clear('$env:RUNNER_TOOL_CACHE')] : []),
      'exit 0',
    ].join('\r\n');
  }
  const clear = (expr: string) =>
    `[ -n "${expr}" ] && [ -d "${expr}" ] && find "${expr}" -mindepth 1 -maxdepth 1 -exec rm -rf {} + 2>/dev/null`;
  return [
    '#!/bin/bash',
    '# Generated by GRC Self-Host. Runs after every job; keeps the runner registration.',
    clear('$GITHUB_WORKSPACE'),
    clear('$RUNNER_TEMP'),
    ...(c.actions ? [clear('$(dirname "$0")/_work/_actions')] : []),
    ...(c.tool ? [clear('$RUNNER_TOOL_CACHE')] : []),
    'exit 0',
  ].join('\n');
}

export interface EnvOptions {
  cleanup: CleanupOptions;
  /** Run the runner with .NET invariant globalization (works around culture bugs, e.g. th-TH). */
  invariantCulture: boolean;
}

/**
 * Writes the cleanup hook and the keys this app manages in the runner's `.env`,
 * keeping any other lines. Takes effect on the next runner start.
 */
export async function writeEnv(dir: string, opts: EnvOptions) {
  const hook = path.join(dir, HOOK_FILE);
  const envFile = path.join(dir, '.env');
  const managed: Record<string, string | undefined> = {
    [HOOK_KEY]: opts.cleanup.enabled ? hook : undefined,
    // The runner starts .ps1 hooks with `powershell -command`, which the default
    // Restricted policy blocks; process scope only, local scripts only.
    PSExecutionPolicyPreference:
      isWin && opts.cleanup.enabled ? 'RemoteSigned' : undefined,
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: opts.invariantCulture
      ? '1'
      : undefined,
  };

  let lines: string[] = [];
  try {
    lines = (await fs.promises.readFile(envFile, 'utf8')).split(/\r?\n/);
  } catch {
    // No .env yet.
  }
  lines = lines.filter(
    (l) => l.trim() && !Object.keys(managed).some((k) => l.startsWith(`${k}=`)),
  );
  for (const [k, v] of Object.entries(managed))
    if (v !== undefined) lines.push(`${k}=${v}`);

  if (opts.cleanup.enabled) {
    await fs.promises.writeFile(hook, hookScript(opts.cleanup) + os.EOL, {
      mode: 0o755,
    });
  } else {
    await fs.promises.rm(hook, { force: true });
  }
  await fs.promises.writeFile(
    envFile,
    lines.length ? lines.join(os.EOL) + os.EOL : '',
  );
}

async function emptyDir(dir: string) {
  let entries: string[];
  try {
    entries = await fs.promises.readdir(dir);
  } catch {
    return;
  }
  await Promise.all(
    entries.map((e) =>
      fs.promises
        .rm(path.join(dir, e), { recursive: true, force: true, maxRetries: 2 })
        .catch(() => {}),
    ),
  );
}

/**
 * "Clean now": empties job workspaces and `_temp`, keeping `_PipelineMapping` and the
 * per-repo folders so the repo mapping survives. `_actions` / `_tool` only when enabled.
 */
export async function cleanWork(dir: string, c: CleanupOptions) {
  const work = path.join(dir, '_work');
  let entries: fs.Dirent[];
  try {
    entries = await fs.promises.readdir(work, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const full = path.join(work, e.name);
    if (e.name === '_PipelineMapping') continue;
    if (e.name === '_actions') {
      if (c.actions) await emptyDir(full);
    } else if (e.name === '_tool') {
      if (c.tool) await emptyDir(full);
    } else if (e.name.startsWith('_')) {
      await emptyDir(full);
    } else {
      // _work/<repo>/<repo> is the workspace: keep each folder, empty its content.
      for (const sub of await fs.promises.readdir(full, {
        withFileTypes: true,
      })) {
        const p = path.join(full, sub.name);
        if (sub.isDirectory()) await emptyDir(p);
        else await fs.promises.rm(p, { force: true }).catch(() => {});
      }
    }
  }
}

/** Deletes a runner folder, retrying while Windows releases file handles. */
export async function deleteDir(dir: string) {
  await fs.promises.rm(dir, {
    recursive: true,
    force: true,
    maxRetries: 10,
    retryDelay: 500,
  });
}
